In [65]:
# Question 1: Version of NumPy

import  numpy as np

In [66]:
np.__version__

'1.21.5'

In [33]:
# Question 2: Number of records in the dataset

import pandas as pd

In [34]:
#data_file_path = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
data_car = pd.read_csv(r"C:\Users\Nauyan\Desktop\data.csv")

In [35]:
data_car

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [36]:
# Question 3: The most popular car manufacturers

data_car.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [37]:
new_data_car=data_car.drop_duplicates('Popularity')

In [38]:
new_data_car.nlargest(n=3,columns='Popularity')

Make       Model  Year             Engine Fuel Type  Engine HP  \
1331  Ford    Aerostar  1995             regular unleaded      135.0   
0      BMW  1 Series M  2011  premium unleaded (required)      335.0   
17    Audi         100  1992             regular unleaded      172.0   

      Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
1331               6.0         AUTOMATIC   rear wheel drive              3.0   
0                  6.0            MANUAL   rear wheel drive              2.0   
17                 6.0            MANUAL  front wheel drive              4.0   

                            Market Category Vehicle Size  Vehicle Style  \
1331                                    NaN      Midsize  Cargo Minivan   
0     Factory Tuner,Luxury,High-Performance      Compact          Coupe   
17                                   Luxury      Midsize          Sedan   

      highway MPG  city mpg  Popularity   MSRP  
1331           22        16        5657   2000  
0              26        19        3916  46135  
17             24        17        3105   2000

In [39]:
# Question 4: Number of unique Audi car models

data_car.groupby('Make')['Model'].nunique()

Make
Acura            18
Alfa Romeo        1
Aston Martin     12
Audi             34
BMW              39
Bentley          18
Bugatti           1
Buick            20
Cadillac         30
Chevrolet        63
Chrysler         19
Dodge            33
FIAT              5
Ferrari          14
Ford             51
GMC              30
Genesis           1
HUMMER            2
Honda            21
Hyundai          22
Infiniti         38
Kia              16
Lamborghini       6
Land Rover       11
Lexus            46
Lincoln          16
Lotus             5
Maserati          8
Maybach           3
Mazda            31
McLaren           4
Mercedes-Benz    40
Mitsubishi       22
Nissan           32
Oldsmobile       18
Plymouth         10
Pontiac          20
Porsche          12
Rolls-Royce      10
Saab              8
Scion             8
Spyker            1
Subaru           16
Suzuki           16
Tesla             1
Toyota           39
Volkswagen       31
Volvo            26
Name: Model, dtype: int64

In [40]:
# Question 5: Number of columns with missing values

print(data_car.isnull().any())
'''The isnull() method returns a DataFrame object where all the values are replaced with a Boolean 
value True for NULL values, and otherwise False.'''

Make                 False
Model                False
Year                 False
Engine Fuel Type      True
Engine HP             True
Engine Cylinders      True
Transmission Type    False
Driven_Wheels        False
Number of Doors       True
Market Category       True
Vehicle Size         False
Vehicle Style        False
highway MPG          False
city mpg             False
Popularity           False
MSRP                 False
dtype: bool


'The isnull() method returns a DataFrame object where all the values are replaced with a Boolean \nvalue True for NULL values, and otherwise False.'

In [41]:
# Question 6: Does the median value change after filling missing values?

data_car['Engine Cylinders'].median()

6.0

In [42]:
data_car['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [43]:
data_car['Engine Cylinders'].fillna(4.0)

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [44]:
data_car['Engine Cylinders'].median()

6.0

In [45]:
# Questions 7: Value of the first element of w

data_car_lotus=data_car.loc[data_car['Make']=='Lotus']

In [46]:
a=data_car_lotus[['Engine HP', 'Engine Cylinders']]

In [47]:
a.drop_duplicates()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [48]:
new=a.drop_duplicates()

In [51]:
x = new.to_numpy()

In [52]:
np.transpose(x)

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [53]:
xt=np.transpose(x)#transpose of x(np array)

In [54]:
np.matmul(xt,x) #multiply xt and x.  used to find out the matrix product of two arrays

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [56]:
xtx=np.matmul(xt,x)

In [57]:
np.linalg.inv(xtx)  #NumPy linear algebra functions   inv()is a numpy library function that computes a matrix's(multiplicative) inverse.

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [60]:
inverse=np.linalg.inv(xtx)

In [61]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [62]:
transpose_xtx=np.transpose(xtx) #convert rows into columns or  columns into rows
np.matmul(inverse,xt) #used to find out the matrix product of two arrays

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [63]:
mul=np.matmul(inverse,xt)
w=np.matmul(mul,y)

In [64]:
w

array([  4.59494481, -63.56432501])